// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: event.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Button int32

const (
	Button_BUTTON_UNKNOWN Button = 0
	Button_BUTTON_OK      Button = 1
	Button_BUTTON_BACK    Button = 2
	Button_BUTTON_START   Button = 3
)

// Enum value maps for Button.
var (
	Button_name = map[int32]string{
		0: "BUTTON_UNKNOWN",
		1: "BUTTON_OK",
		2: "BUTTON_BACK",
		3: "BUTTON_START",
	}
	Button_value = map[string]int32{
		"BUTTON_UNKNOWN": 0,
		"BUTTON_OK":      1,
		"BUTTON_BACK":    2,
		"BUTTON_START":   3,
	}
)

func (x Button) Enum() *Button {
	p := new(Button)
	*p = x
	return p
}

func (x Button) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Button) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[0].Descriptor()
}

func (Button) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[0]
}

func (x Button) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Button.Descriptor instead.
func (Button) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

type ButtonAction int32

const (
	ButtonAction_ACTION_UNKNOWN ButtonAction = 0
	ButtonAction_ACTION_PRESS   ButtonAction = 1
	ButtonAction_ACTION_RELEASE ButtonAction = 2
)

// Enum value maps for ButtonAction.
var (
	ButtonAction_name = map[int32]string{
		0: "ACTION_UNKNOWN",
		1: "ACTION_PRESS",
		2: "ACTION_RELEASE",
	}
	ButtonAction_value = map[string]int32{
		"ACTION_UNKNOWN": 0,
		"ACTION_PRESS":   1,
		"ACTION_RELEASE": 2,
	}
)

func (x ButtonAction) Enum() *ButtonAction {
	p := new(ButtonAction)
	*p = x
	return p
}

func (x ButtonAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ButtonAction) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[1].Descriptor()
}

func (ButtonAction) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[1]
}

func (x ButtonAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ButtonAction.Descriptor instead.
func (ButtonAction) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

type SwitchPosition int32

const (
	SwitchPosition_SWITCH_UNKNOWN  SwitchPosition = 0
	SwitchPosition_SWITCH_BUSY     SwitchPosition = 1
	SwitchPosition_SWITCH_CUSTOM   SwitchPosition = 2
	SwitchPosition_SWITCH_OFF      SwitchPosition = 3
	SwitchPosition_SWITCH_APPS     SwitchPosition = 4
	SwitchPosition_SWITCH_SETTINGS SwitchPosition = 5
)

// Enum value maps for SwitchPosition.
var (
	SwitchPosition_name = map[int32]string{
		0: "SWITCH_UNKNOWN",
		1: "SWITCH_BUSY",
		2: "SWITCH_CUSTOM",
		3: "SWITCH_OFF",
		4: "SWITCH_APPS",
		5: "SWITCH_SETTINGS",
	}
	SwitchPosition_value = map[string]int32{
		"SWITCH_UNKNOWN":  0,
		"SWITCH_BUSY":     1,
		"SWITCH_CUSTOM":   2,
		"SWITCH_OFF":      3,
		"SWITCH_APPS":     4,
		"SWITCH_SETTINGS": 5,
	}
)

func (x SwitchPosition) Enum() *SwitchPosition {
	p := new(SwitchPosition)
	*p = x
	return p
}

func (x SwitchPosition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SwitchPosition) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[2].Descriptor()
}

func (SwitchPosition) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[2]
}

func (x SwitchPosition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SwitchPosition.Descriptor instead.
func (SwitchPosition) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

type NormalizedButtonEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Button        Button                 `protobuf:"varint,2,opt,name=button,proto3,enum=busybar.event.Button" json:"button,omitempty"`
	Action        ButtonAction           `protobuf:"varint,3,opt,name=action,proto3,enum=busybar.event.ButtonAction" json:"action,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NormalizedButtonEvent) Reset() {
	*x = NormalizedButtonEvent{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizedButtonEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizedButtonEvent) ProtoMessage() {}

func (x *NormalizedButtonEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizedButtonEvent.ProtoReflect.Descriptor instead.
func (*NormalizedButtonEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *NormalizedButtonEvent) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *NormalizedButtonEvent) GetButton() Button {
	if x != nil {
		return x.Button
	}
	return Button_BUTTON_UNKNOWN
}

func (x *NormalizedButtonEvent) GetAction() ButtonAction {
	if x != nil {
		return x.Action
	}
	return ButtonAction_ACTION_UNKNOWN
}

func (x *NormalizedButtonEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type NormalizedSwitchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Position      SwitchPosition         `protobuf:"varint,2,opt,name=position,proto3,enum=busybar.event.SwitchPosition" json:"position,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NormalizedSwitchEvent) Reset() {
	*x = NormalizedSwitchEvent{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizedSwitchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizedSwitchEvent) ProtoMessage() {}

func (x *NormalizedSwitchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizedSwitchEvent.ProtoReflect.Descriptor instead.
func (*NormalizedSwitchEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

func (x *NormalizedSwitchEvent) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *NormalizedSwitchEvent) GetPosition() SwitchPosition {
	if x != nil {
		return x.Position
	}
	return SwitchPosition_SWITCH_UNKNOWN
}

func (x *NormalizedSwitchEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type NormalizedEncoderEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Delta         int32                  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NormalizedEncoderEvent) Reset() {
	*x = NormalizedEncoderEvent{}
	mi := &file_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizedEncoderEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizedEncoderEvent) ProtoMessage() {}

func (x *NormalizedEncoderEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizedEncoderEvent.ProtoReflect.Descriptor instead.
func (*NormalizedEncoderEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

func (x *NormalizedEncoderEvent) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *NormalizedEncoderEvent) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *NormalizedEncoderEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type NormalizedEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Device    string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*NormalizedEvent_Button
	//	*NormalizedEvent_Switch
	//	*NormalizedEvent_Encoder
	Event         isNormalizedEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NormalizedEvent) Reset() {
	*x = NormalizedEvent{}
	mi := &file_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizedEvent) ProtoMessage() {}

func (x *NormalizedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizedEvent.ProtoReflect.Descriptor instead.
func (*NormalizedEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{3}
}

func (x *NormalizedEvent) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *NormalizedEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *NormalizedEvent) GetEvent() isNormalizedEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *NormalizedEvent) GetButton() *NormalizedButtonEvent {
	if x != nil {
		if x, ok := x.Event.(*NormalizedEvent_Button); ok {
			return x.Button
		}
	}
	return nil
}

func (x *NormalizedEvent) GetSwitch() *NormalizedSwitchEvent {
	if x != nil {
		if x, ok := x.Event.(*NormalizedEvent_Switch); ok {
			return x.Switch
		}
	}
	return nil
}

func (x *NormalizedEvent) GetEncoder() *NormalizedEncoderEvent {
	if x != nil {
		if x, ok := x.Event.(*NormalizedEvent_Encoder); ok {
			return x.Encoder
		}
	}
	return nil
}

type isNormalizedEvent_Event interface {
	isNormalizedEvent_Event()
}

type NormalizedEvent_Button struct {
	Button *NormalizedButtonEvent `protobuf:"bytes,3,opt,name=button,proto3,oneof"`
}

type NormalizedEvent_Switch struct {
	Switch *NormalizedSwitchEvent `protobuf:"bytes,4,opt,name=switch,proto3,oneof"`
}

type NormalizedEvent_Encoder struct {
	Encoder *NormalizedEncoderEvent `protobuf:"bytes,5,opt,name=encoder,proto3,oneof"`
}

func (*NormalizedEvent_Button) isNormalizedEvent_Event() {}

func (*NormalizedEvent_Switch) isNormalizedEvent_Event() {}

func (*NormalizedEvent_Encoder) isNormalizedEvent_Event() {}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\rbusybar.event\"\xb1\x01\n" +
	"\x15NormalizedButtonEvent\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12-\n" +
	"\x06button\x18\x02 \x01(\x0e2\x15.busybar.event.ButtonR\x06button\x123\n" +
	"\x06action\x18\x03 \x01(\x0e2\x1b.busybar.event.ButtonActionR\x06action\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\x88\x01\n" +
	"\x15NormalizedSwitchEvent\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x129\n" +
	"\bposition\x18\x02 \x01(\x0e2\x1d.busybar.event.SwitchPositionR\bposition\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"d\n" +
	"\x16NormalizedEncoderEvent\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x05R\x05delta\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x93\x02\n" +
	"\x0fNormalizedEvent\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12>\n" +
	"\x06button\x18\x03 \x01(\v2$.busybar.event.NormalizedButtonEventH\x00R\x06button\x12>\n" +
	"\x06switch\x18\x04 \x01(\v2$.busybar.event.NormalizedSwitchEventH\x00R\x06switch\x12A\n" +
	"\aencoder\x18\x05 \x01(\v2%.busybar.event.NormalizedEncoderEventH\x00R\aencoderB\a\n" +
	"\x05event*N\n" +
	"\x06Button\x12\x12\n" +
	"\x0eBUTTON_UNKNOWN\x10\x00\x12\r\n" +
	"\tBUTTON_OK\x10\x01\x12\x0f\n" +
	"\vBUTTON_BACK\x10\x02\x12\x10\n" +
	"\fBUTTON_START\x10\x03*H\n" +
	"\fButtonAction\x12\x12\n" +
	"\x0eACTION_UNKNOWN\x10\x00\x12\x10\n" +
	"\fACTION_PRESS\x10\x01\x12\x12\n" +
	"\x0eACTION_RELEASE\x10\x02*~\n" +
	"\x0eSwitchPosition\x12\x12\n" +
	"\x0eSWITCH_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vSWITCH_BUSY\x10\x01\x12\x11\n" +
	"\rSWITCH_CUSTOM\x10\x02\x12\x0e\n" +
	"\n" +
	"SWITCH_OFF\x10\x03\x12\x0f\n" +
	"\vSWITCH_APPS\x10\x04\x12\x13\n" +
	"\x0fSWITCH_SETTINGS\x10\x05B2Z0github.com/brotherlogic/busybar-bridge/pkg/pb;pbb\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_event_proto_goTypes = []any{
	(Button)(0),                    // 0: busybar.event.Button
	(ButtonAction)(0),              // 1: busybar.event.ButtonAction
	(SwitchPosition)(0),            // 2: busybar.event.SwitchPosition
	(*NormalizedButtonEvent)(nil),  // 3: busybar.event.NormalizedButtonEvent
	(*NormalizedSwitchEvent)(nil),  // 4: busybar.event.NormalizedSwitchEvent
	(*NormalizedEncoderEvent)(nil), // 5: busybar.event.NormalizedEncoderEvent
	(*NormalizedEvent)(nil),        // 6: busybar.event.NormalizedEvent
}
var file_event_proto_depIdxs = []int32{
	0, // 0: busybar.event.NormalizedButtonEvent.button:type_name -> busybar.event.Button
	1, // 1: busybar.event.NormalizedButtonEvent.action:type_name -> busybar.event.ButtonAction
	2, // 2: busybar.event.NormalizedSwitchEvent.position:type_name -> busybar.event.SwitchPosition
	3, // 3: busybar.event.NormalizedEvent.button:type_name -> busybar.event.NormalizedButtonEvent
	4, // 4: busybar.event.NormalizedEvent.switch:type_name -> busybar.event.NormalizedSwitchEvent
	5, // 5: busybar.event.NormalizedEvent.encoder:type_name -> busybar.event.NormalizedEncoderEvent
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	file_event_proto_msgTypes[3].OneofWrappers = []any{
		(*NormalizedEvent_Button)(nil),
		(*NormalizedEvent_Switch)(nil),
		(*NormalizedEvent_Encoder)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		EnumInfos:         file_event_proto_enumTypes,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
